### ISSUE TITLE
activation

### ISSUE THREAD

**Issue by tarbear123** [omeryanar/FileExplorer#10]
how i do i get it working?

**Comment by omeryanar** [comment]
If you just want to run it, all you have to do is unzip the latest release to a folder and run FileExplorer.exe.
https://github.com/omeryanar/FileExplorer/releases/latest/download/FileExplorer.zip

If you want to build, you need a commercial DevExpress WPF Subscription license.
https://www.devexpress.com/products/net/controls/wpf
