### ISSUE TITLE
Register it as default file explorer

### ISSUE THREAD

**Issue by digitalblossom** [omeryanar/FileExplorer#11]
Is it possible to use this as the default explorer over the windows one? I think Explorer++ has this feature. Great work by the way, this is exactly what I was looking for

**Comment by omeryanar** [comment]
Yes, it is possible, but this requires a manual registry edit as it needs administrative privileges.

- Create a new text file with a .reg extension (Windows Registry Script), e.g. FileExplorer.reg.

- Paste the following text into it (by changing the path of FileExplorer.exe to where it is located on your system):

`Windows Registry Editor Version 5.00
 
[HKEY_CLASSES_ROOT\Drive\shell]
@="open"
 
[HKEY_CLASSES_ROOT\Drive\shell\open]
 
[HKEY_CLASSES_ROOT\Drive\shell\open\command]
@="\"C:\\FileExplorer\\FileExplorer.exe\" %1"
 
[HKEY_CLASSES_ROOT\Directory\shell]
@="open"
 
[HKEY_CLASSES_ROOT\Directory\shell\open]
 
[HKEY_CLASSES_ROOT\Directory\shell\open\command]
@="\"C:\\FileExplorer\\FileExplorer.exe\" %1"`

**Comment by omeryanar** [comment]
In this case I would also suggest adding FileExplorer to Windows startup (using the Options dialog)

**Comment by schlumpf90** [comment]
Hi !
The trick with the registry settings works fine!
But: if the foldername has blanks and you make a doubleclick from the Windows Explorer on it, then the FileExplorer opens but not in this directory. The problem are definitly the blanks.

Thx

**Comment by JaneValleyhasBtaken** [comment]
What if I want to reset back to default file explorer, what should I do?
