### ISSUE TITLE
Add an option to not expand Navigation Pane to open folder

### ISSUE THREAD

**Issue by Toxijuice** [omeryanar/FileExplorer#17]
A feature I really appreciate of the Windows Explorer is that it is possible to disable the expanding of the open folder in the Navigation Pane. I often use the Navigation Pane as a list of shortcuts to my Quick access folders and top-level directories, and when drilling far down into folders, it becomes difficult to navigate the Navigation Pane to fine those shortcuts.

_The option in question from Windows Explorer_
![2022-11-08-190020](https://user-images.githubusercontent.com/6213564/200728365-857494da-754f-4925-bd04-efae0ebe3361.png)

**Comment by omeryanar** [comment]
Added as an option to: View > Panes > Navigation Pane > Expand to open folder
