### ISSUE TITLE
Option: static icon in the Taskbar

### ISSUE THREAD

**Issue by DavidBevi** [omeryanar/FileExplorer#21]
Hi! I'd like to suggest a little thing I'd really like to see: the ability to always display the same icon in the task bar, regardless of the folder currently open in FileExplorer.

I ask this because _Quick Access_, _My Computer_, and many more system folders override the yellow folder icon, which is what I look for when I want to use FileExplorer.

Definitely not a big issue, but it would be a nice touch!

**Comment by DuckEater** [comment]
It appears to me that if you pin FileExplorer to the taskbar, the icon becomes static.

**Comment by DavidBevi** [comment]
To me pinning FileExplorer to the taskbar changes nothing, "special" folders still get their "special" icon in the taskbar.

**Comment by omeryanar** [comment]
Two new settings added to the 'Options' pane for static Window icon and title:
(Included in the latest v2.0 release)

![Static Taskbar](https://user-images.githubusercontent.com/34584700/221008876-ae8e0536-e175-436d-aa77-87bd7fa74b90.png)
