### ISSUE TITLE
Build from source instructions

### ISSUE THREAD

**Issue by Bristopher** [omeryanar/FileExplorer#29]
I'm really interested in trying something like this and want to build form source and was hoping you could add the prereqs and such, thanks!

**Comment by omeryanar** [comment]
I've created a wiki page for the project: https://github.com/omeryanar/FileExplorer/wiki 
The only thing you may not have is a WPF Component Subscription from DevExpress.
(I'm assuming you already have Visual Studio, for example VS Community Edition.)
