### ISSUE TITLE
Remove the white fade in when scrolling

### ISSUE THREAD

**Issue by paul-arg** [omeryanar/FileExplorer#33]
Hello,
Thank you for creating this incredible file manager!

Is it possible to remove the white fade in animation that occurs when scrolling up and down? And display items immediately

Thanks

**Comment by omeryanar** [comment]
Thanks.
The reason for the fade effect is the virtualization of the file list view. To display large folders quickly and as memory efficient as possible, the file list view renders only visible items. As you scroll down, new items are rendered. For a smooth scrolling experience, a fade in animation is shown. I will consider adding a setting that disables virtualization, but keep in mind that this setting will slow down the display of large files and increase memory consumption.

**Comment by omeryanar** [comment]
New Setting for Virtualization is added in v2.3
