### ISSUE TITLE
Wrong name of the layout field when the toolbars are minimized

### ISSUE THREAD

**Issue by 1andro1** [omeryanar/FileExplorer#36]
Hello,

I just noticed that when I minimize the toolbars the name of the layout becomes themes:

![image](https://user-images.githubusercontent.com/79647326/229368691-9479fc3c-f29c-4cb4-be37-5be99951992b.png)

![image](https://user-images.githubusercontent.com/79647326/229368721-768689c0-80d1-432d-8c0e-27227cdf4a17.png)
 
I am with the news version of the program on windows 10.

Best Regards,
Adriyan

**Comment by omeryanar** [comment]
Good catch!
I've fixed it, will be included in the next release.
