### ISSUE TITLE
PDF Pluging is disabled once it encounters and error

### ISSUE THREAD

**Issue by 1andro1** [omeryanar/FileExplorer#38]
Hello,

this situation is little bit ridiculous, but I encountered it anyway. So if I change a txt file to pdf file and try to see the preview of the file the program issues an error, which is ok. However, after that, preview of the pfd files does not work anymore even with real pdf files. Once the program is restarted the plugin works again correctly. The error which the program issues is:

![image](https://user-images.githubusercontent.com/79647326/230028170-6a55c5f8-beeb-4286-a253-7ce8cafec5f9.png)

Best Regards,
Adriyan

**Comment by omeryanar** [comment]
Yes, there is a bug in PDF preview extension. I will fix it in the next release.

**Comment by omeryanar** [comment]
Fixed in v2.3
