### ISSUE TITLE
Several Sugestions

### ISSUE THREAD

**Issue by 1andro1** [omeryanar/FileExplorer#42]
Hello Omer,

I would like to give you some suggestion for the programs. I am using the program in content view and all suggestions apply only for that mode:

- inline renaming
- multiple file/folder select within different folders
- 2 or 3 additional vertical panes. I am using a 32 inch screen and there is a lot of space which is not used when the preview pane is disabled
- fast filtering. I saw that there is a filtering but it takes a lot of time to make that filtering. Sometimes I just want to find the file faster by typing 2-3 letters. The other options is jump to a file/folder like in the windows explorer
- possibility to add extensions to the extensions list in the preview extensions. As example, in the text file extension preview additional files can be added like csv, reg ro some other types
- folder creation. Currently when I right click on one folder and want to make a folder inside that folder it does not work. The program creates the folder in the main folder in which it is. As example if I am in D:\ and right click on D:\New Folder to create a New Folder 2 the program will crate the folder in D:\.
- options the quick access to be always expanded
- shortcuts for fast up one level. As example if I have expanded one folder and it has a lot of files and I am somewhere in the middle, it will be good if I can go back to the expanded folder faster with one key or mouse gesture.

If you find some of the suggestions useful I will be happy. If you find the suggestions pointless you can close the ticket. 

Best Regards,
Adriyan

**Comment by omeryanar** [comment]
Thanks for your suggestions, they are definitely not pointless.
My comments are below:

- inline renaming
_This is in my TO-DO List._

- multiple file/folder select within different folders
_This is a deliberate limitation for drag-and-drop support. Errors may occur if files in different folders are dragged and dropped into one of these folders._

- 2 or 3 additional vertical panes. 
_I'm not thinking to implement this but note that you can easily achieve the same result by opening multiple windows (by detaching tabs using drag & drop as in web browser apps) and aligning those windows on your desktop._

- fast filtering. 
_This is in my TO-DO List._

- possibility to add extensions to the extensions list in the preview extensions.
_This is already possible. You can add the extension you want as Preferred in the Extensions window:_ https://github.com/omeryanar/FileExplorer#preview-pane 

- folder creation.
_Done. You can now create files and folders in the selected folder. (v2.4)_

- options the quick access to be always expanded
_I think this is also possible. "Expand To Open Folder" should be checked in View >Navigation Pane_

- shortcuts for fast up one level.
_This is possible in content view. You can use arrow keys to navigate between folders._

**Comment by 1andro1** [comment]
**2 or 3 additional vertical panes.**
I'm not thinking to implement this but note that you can easily achieve the same result by opening multiple windows (by detaching tabs using drag & drop as in web browser apps) and aligning those windows on your desktop.
-- in my computer the windows does not allow multiple instances of the program. Maybe I am doing something wrong?

**multiple file/folder select within different folders**
This is a deliberate limitation for drag-and-drop support. Errors may occur if files in different folders are dragged and dropped into one of these folders.
-- I am working with folders with many sub-folders and files. Sometimes I need to move files from different folder in one folder or to delete them. It will be faster to be able to select all those files, but this is my use case. It is possible that other does not need it.

**folder creation.**
Done. You can now create files and folders in the selected folder. (v2.4)
-- I tested it. On local drive works but on the network drive the program does not refresh automatically and the new folder is not visible even though it is there. When I press refresh button in a content view the folder is still not shown, but if I make the refresh when I am in the folder in which I created the new folder the new folder is shown. The auto refresh does not work, thought. Unfortunately, cannot send you the log file, as there were 3 errors inside it and to check whether the errors are because of the auto refresh, I delete the log file thinking that the program will create it again once an error is encountered. When I tested the creation of the folders and refresh again the log file was not created by the program. I do not know whether I mess up.

**options the quick access to be always expanded**
I think this is also possible. "Expand To Open Folder" should be checked in View >Navigation Pane
-- my idea is to make shortcuts for some folders for fast access. When I enable the "Expand To Open Folder" the folder expands together with my movement in the sub-folders (when I enter the folder) and when I am deep in the tree the fast access is lost. But it is not big deal. 
Would it be possible the folders in the Quick Access to be arranged somehow?

**shortcuts for fast up one level.**
This is possible in content view. You can use arrow keys to navigate between folders.
-- works!

Could you tell me what decides the background of the extensions. As example the doc, txt, files are with white background while xls, csv are with dark? I am using dark mode on windows and in the FileExplorer.

Many thanks for your efforts!

Best Regards,
Adriyan

**Comment by 1andro1** [comment]
just saw, as I was trying to preview one pdf file and I was unable to preview it, the log file was created wit several error inside (access denied). So it seems there is no error issued from the program at the refresh.

**Comment by omeryanar** [comment]
> Could you tell me what decides the background of the extensions. As example the doc, txt, files are with white background while xls, csv are with dark? I am using dark mode on windows and in the FileExplorer.

The background depends on the file itself. Because PDF and Word documents are basically paper-based documents, they include a white background color by default. The only way to change them is to modify the file itself. The background color of other documents depends on the component. Most of the components support dark mode. I use AvalonEdit when previewing text based files, it supports dark mode but in a slightly different way. I'll look into it whether it's possible to switch to dark mode in AvalonEdit when the app theme changed.

**Comment by omeryanar** [comment]
> additional feature: options for opening the last session with the open tabs and places before closing the program.

This is implemented in v3.1, so I'm closing this issue.
