### ISSUE TITLE
Files from SMB server gets permanently deleted

### ISSUE THREAD

**Issue by Dxhs** [omeryanar/FileExplorer#44]
When I browse a network disk (SMB) at work, the delete options permanently deletes without using the recycle bin. Is this a bug?

**Comment by mamift** [comment]
This is how SMB works I'm pretty sure - even when you use Windows' built-in File Explorer, deleting a file over a network share via SMB. I get the same behaviour using MacOS Finder - there's no moving the file to the trash or anything - just a prompt and if you say yes to delete, then it's permanently deleted.

Just tested on Windows 11 using Windows' file explorer and I get this prompt:
![image](https://github.com/omeryanar/FileExplorer/assets/2508444/0bcaf4a5-1b14-47fc-a6a3-f103e72d5702)

There's no option to move it to the recycle bin on your machine or the remote machine.

**Comment by omeryanar** [comment]
> This is how the SMB protocol works I'm pretty sure - it's not something that can be changed from the app - even when you use Windows' built-in File Explorer, deleting a file over a network share via SMB behaves the same. I get the same behaviour using MacOS Finder - there's no moving the file to the trash or anything - just a prompt and if you say yes to delete, then it's permanently deleted.
> 
> Just tested on Windows 11 using Windows' file explorer and I get this prompt: ![image](https://private-user-images.githubusercontent.com/2508444/264190353-0bcaf4a5-1b14-47fc-a6a3-f103e72d5702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjAxODAsIm5iZiI6MTcwNjQ1OTg4MCwicGF0aCI6Ii8yNTA4NDQ0LzI2NDE5MDM1My0wYmNhZjRhNS0xYjE0LTQ3ZmMtYTZhMy1mMTAzZTcyZDU3MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTYzODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZhODNjMTI2NmQzNDQyMzNhN2QzYjgxYzBiMTgzNmRhMzI0MGM2YzhiZjUzYzFmYTIzODYzYjVmZjg5NzQxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uloaxzEu1pqVD7qiwICCiOzWsZTvDHlQml_bchjPT7o)
> 
> There's no option to move it to the recycle bin on your machine or the remote machine. If you want to be able to recover a deleted file from an SMB share, you need to enable File history or Volume shadow copy before-hand on the drive of the remote machine.

You are right. There is no way to send a network shared file to recycle bin. However, windows make this clear by disabling Recycle button. So I labeled this issue as bug, and fixed in version 3.0
