### ISSUE TITLE
Preview extensions not registering

### ISSUE THREAD

**Issue by p2bilt** [omeryanar/FileExplorer#46]
This extension contains an error and cannot be enabled. Refer to error details for more information:

"Could not load file or assembly 'FileExplorer.Extension.PdfPreview, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)"

**Comment by omeryanar** [comment]
I couldn't reproduce this problem, it was probably caused by a missing DLL file. Please try the current version (v2.5) and reopen the issue if the problem occurs again.

**Comment by stoph88** [comment]
Same.  None of the extensions work at all.
