### ISSUE TITLE
Duplicating line when renaming the same name between lower/upper case, in "Content/tree" view mode

### ISSUE THREAD

**Issue by dougamolina** [omeryanar/FileExplorer#48]
Hi! 

I've been using your software for a couple of hours and that tree view is really helping me organize my projects folders, thanks a lot for that!

I've noticed when i rename a file to the same name but in a different case, for example "my file" to "my File" (with an upper case "F") that line instead of just updating it also duplicates, and even if i refresh that doesn't change much, so i have to restart the program.

Here is a screen capture.
![FileExplorer_BxNq5fLnEq](https://github.com/omeryanar/FileExplorer/assets/38884996/123bd4d6-bc00-4589-9ddf-10ffa6600b76)

Thanks!

**Comment by omeryanar** [comment]
Thanks for the screen capture. I fixed it, will be included in the next release (v2.5).
