### ISSUE TITLE
Remove/hide default entries from Quick Access

### ISSUE THREAD

**Issue by DavidBevi** [omeryanar/FileExplorer#49]
I'd like to permanently remove or hide many default items from Quick Access (because I use different folders, so Quick Access shows me empty folders).

In _Win_ Explorer I did it, but I guess FileExplorer has its own Quick Access list, which I'm not finding a way to edit.

**Comment by omeryanar** [comment]
Latest version (v2.5) allows removing user folders (documents, videos etc.) from quick access.
