### ISSUE TITLE
Annoying behavior for down arror key

### ISSUE THREAD

**Issue by arttsai** [omeryanar/FileExplorer#50]
This is a great application.

But there's an annoying behavior for me.  When I press down arror key through the left pane, I expect it will go to the next sibling file/folder.  But it will navigate to the next sibling folder and expand it.  In this situation, it will make me to press hundreds of down arrow key to arrive at the destination that I want. 

Is there an option that I can configure to navigate to the next sibling without expanding it? 

The same behavior goes to the up arrow key.  

Thanks.

**Comment by omeryanar** [comment]
You're right. It auto expands selected folder in the left pane. It's a good idea to have an option for this behavior.

**Comment by arttsai** [comment]
Wow.  Thank you.

**Comment by omeryanar** [comment]
![image](https://github.com/omeryanar/FileExplorer/assets/34584700/e44b5c44-7e46-4ca5-ac86-691ee54d9689)

I added an option in View => Navigation Pane => Expand to open folder (v3.0). The behavior is similar to windows explorer.

**Comment by arttsai** [comment]
Wow! Thanks.  It'd help a lot.

**Comment by Diogo-Rossi** [comment]
Hey @omeryanar, I just found this option and it makes the software even better! Thank you!

Can you add this option also to the folders that we select in the main pane?

The current behaviour is: entering in a folder in the main pane auto expands the matching folder in the left pane.

Could you add to not expand the matching folder of the last pane?

This software is the best I found!
