### ISSUE TITLE
Layout related questions

### ISSUE THREAD

**Issue by Alex527** [omeryanar/FileExplorer#51]
Great app so far, just a couple of questions about applying layout.

1. When I create and save a layout for a folder, it's applied to every other folder and drive. When I load default layout it works fine until I navigate to the folder with custom layout, it's applied to every other folder automatically again. Looks like a bug to me.

2. Could you make unified sorting a part of layout instead of system-wide setting? That would greatly improve usability.

3. I haven't found a way to access Recycle Bin. Windows Explorer options with shell from google articles didn't help. Could you maybe add it to Quick Launch section?

**Comment by deedeelu** [comment]
Possibly related to layout persistence (or lack thereof?). I use AutoHotKey to open my downloads folder with a hotkey that's mapped to the FileExplorer.exe path with "path\to\Downloads\Folder" appended (looks like  Run,  C:\Program Files\FileExplorer\FileExplorer.exe "C:\Users\USERNAME\Downloads". The new window/tab always opens with the default layout applied even though I've saved a layout for the Downloads folder.

**Comment by omeryanar** [comment]
> Great app so far, just a couple of questions about applying layout.
> 
> 1. When I create and save a layout for a folder, it's applied to every other folder and drive. When I load default layout it works fine until I navigate to the folder with custom layout, it's applied to every other folder automatically again. Looks like a bug to me.
> 2. Could you make unified sorting a part of layout instead of system-wide setting? That would greatly improve usability.
> 3. I haven't found a way to access Recycle Bin. Windows Explorer options with shell from google articles didn't help. Could you maybe add it to Quick Launch section?

Thanks.
1.  I did this on purpose, but now that I think about it the way you described it, it seems like a bug to me as well. Fixed in v3.0
2.  This is a bit difficult to implement without breaking old layout saving system, but I will look into it.
3.  Yes, Recycle Bin is not available because there is no standard .NET function to retrieve it. Maybe there is a nuget package or something,  if I find a good one I'll add it.
​

**Comment by omeryanar** [comment]
> Possibly related to layout persistence (or lack thereof?). I use AutoHotKey to open my downloads folder with a hotkey that's mapped to the FileExplorer.exe path with "path\to\Downloads\Folder" appended (looks like Run, C:\Program Files\FileExplorer\FileExplorer.exe "C:\Users\USERNAME\Downloads". The new window/tab always opens with the default layout applied even though I've saved a layout for the Downloads folder.

You are right, saved layout is not applied if it is opened from outside. It seems there is a bug, I will fix it in the next version.

**Comment by omeryanar** [comment]
Fixed in v3.1. For Recycle Bin, have opened a new issue  #64 , so I'm closing this one.
