### ISSUE TITLE
Keyboards shortcut

### ISSUE THREAD

**Issue by Xiarno** [omeryanar/FileExplorer#53]
Add multiple common shortcut with the possibility to edit the shortcut key.

The most important I'm thinking about are:

- New tab
- Clone current tab
- New folder
- Undo closing recent tab (Recursive. Aka can be done multiple time)
Probably some other that I'm not thinking about.

**Comment by Xiarno** [comment]
Btw, it says that you can "CTRL + Click on a folder to open a new tab" but either I'm not understanding how exactly to do it or it doesn't work.

**Comment by omeryanar** [comment]
> Btw, it says that you can "CTRL + Click on a folder to open a new tab" but either I'm not understanding how exactly to do it or it doesn't work.

This is fixed in v3.0 
Similar to web browsers, Ctrl+T can be used to open new tab. Other shortcuts can be seen in the context menu.

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/ad784361-7d19-47b9-8ca8-02b4e4c4f25a)
