### ISSUE TITLE
Request: add option to use different date/time formats

### ISSUE THREAD

**Issue by DavidBevi** [omeryanar/FileExplorer#57]
- I'm just mad with MDY format (USA), it's illogic and confusing 😕, please let me use DMY and/or YMD (standards used [pretty much everywhere](https://en.wikipedia.org/wiki/Date_format_by_country) outside USA 😊) 
- 24h format is just a nice-to-have, I can live without it

**Comment by omeryanar** [comment]
![image](https://github.com/omeryanar/FileExplorer/assets/34584700/79a7e08a-8a2f-4d40-a0c2-6f10fb58c4c7)

I added an option to change datetime format. You can choose one of the options available, or enter your preferred format according to custom datetime formats: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
