### ISSUE TITLE
Network attached drivers are not updated

### ISSUE THREAD

**Issue by 1andro1** [omeryanar/FileExplorer#60]
Hello,

in case a folder in a network attached driver is open in the Explorer, the changes in folders (renaming of a file, creation of new file, deletion of a file...) are not actualized in the Explorer. A person must enter in the folder and make manual refresh. I am using the program in content layout.
When the folder is in a local drive everything is ok.

Best Regards,
Adriyan

**Comment by omeryanar** [comment]
Thanks for the info. This is a limitation of [FileSystemWatcher](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0), the class responsible for change tracking. It somehow loses the connection and stops sending file/directory change events. I will add a recurrent connection refresh feature to fix this issue.
