### ISSUE TITLE
Option to disable file/folder rename based on mouse click (slow second click)

### ISSUE THREAD

**Issue by jefflord** [omeryanar/FileExplorer#62]
I'd love an option to disable entering rename mode by mouse click so that only F2 or the context menu could be used to rename the file/folder.

The reason for this request is that it's too easy to inadvertently enter rename mode. This is primarily because the state of the mode is not reset when the application loses focus. What this means is that if a file or folder is selected, then another program is clicked, and then returning to this program by clicking the file (which may have been previously focused or internally selected, perhaps a long time ago), it will immediately enter rename mode upon clicking, when the intention may have simply been to refocus the application.

In Windows File Explorer, this behavior does not occur. Both clicks needed to enter rename mode must occur while the application has focus.

I understand there's a workaround (to change my years of trained behavior) by clicking something other than the file name, but that seems impractical to me, since the "name" is synonymous with the file itself, and the other information in the row pertains to the file's data.

Additionally, there appears to be another bug. Clicking the blank area in a folder should deselect all files and folders, but it does not.

Furthermore, there seems to be another bug. The "Select None" button only visually deselects all items. Pressing F2 will still enter rename mode for the selected file, even after "Select None" has been clicked.

**Comment by omeryanar** [comment]
All three issues fixed in the new version (v3.1)

**Comment by jefflord** [comment]
Amazing, so fast and so much better! 

Thank you!
