### ISSUE TITLE
[request] Theme customization

### ISSUE THREAD

**Issue by 70V07** [omeryanar/FileExplorer#68]
I suggest to add a feature for customize or/and make themes
or if to much complicate... just add an option for choose accent color

_expecialy add the border with accent color in all FileExplorer window_

**Comment by omeryanar** [comment]
Unfortunately, the component library I use is not very easy to customize. However, you can choose one of the predefined colors of a theme, for example Visual Studio or Office themes come with 7-8 predefined palette colors.

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/f63951f2-dae5-4e0d-994f-6e25f4a79a98)
