### ISSUE TITLE
Integration of context menu from Windows Explorer

### ISSUE THREAD

**Issue by schlumpf90** [omeryanar/FileExplorer#69]
Hi!
It's a great feature, to add individual context menus in FileExplorer!
But I'm missing some context menus from the Windows Explorer and I don't want to add all of these missing menus to FileExplorer.
So it would be great to show all of the context menus from Windows Explorer in an new group in the FileExplorer context menu.

Best regards and thx !!

**Comment by omeryanar** [comment]
This is implemented in v3.4
You can CTRL + Right click on files or folders to display standard Windows context menu.

https://github.com/omeryanar/FileExplorer?tab=readme-ov-file#standard-windows-and-custom-context-menu
