### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by TheBauwssss** [omeryanar/FileExplorer#7]
I was wondering if it would be possible to get a copy of the source code for the FileExplorer application?

Kind regards,

DaBauws 😄 

> My sincere apologies if this has been asked before, or if the source code is available somewhere I haven't looked before! Additionally; I am aware that this is not really an issue per-say but I honestly didn't know where else I could ask this question. Besides, I reckon that I am not the only person wondering this very same question; especially after seeing the virtually empty repository.

**Comment by omeryanar** [comment]
I've uploaded the source code to the repository. Unfortunately, it requires a commercial subscription to build:
https://www.devexpress.com/products/net/controls/wpf/ 
This is why I didn't share it in the first place, not sure it would help.
Anyway, here is the source code, I hope it will be helpful :)
Kind regards...

**Comment by TheBauwssss** [comment]
Thank you very much! 😄
