### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by bakipollat** [omeryanar/FileExplorer#70]
Hi, not sure if these can be implemented but it would be great to have these features;

1.  Batch expand file tree of all the folders in content view with a shortcut like shift or alt
2.  Undo feature, same as the original windows explorer with ctrl+z

Also, sort of bug but not sure how to recreate, we have experienced some issues with interface while copying files, when we copy through file explorer, it shows two of the same item in file explorer, while in original directory in windows there are only one file. Just putting it here in case someone else who experienced this can explain how to recreate. Thanks ✌

**Comment by aderchox** [comment]
First off, this is a great great tool for my need, I absolutely love this feature that I can click on a tree view item and it both expands it and opens it in the window. Thanks @omeryanar .
__I also have a request for a small UI improvement:__ Please let the user decide if they want that blue bar on the size column. I personally don't need that visuals, I just want the size number, however, it's not currently possible to disable it.

**Comment by omeryanar** [comment]
> First off, this is a great great tool for my need, I absolutely love this feature that I can click on a tree view item and it both expands it and opens it in the window. Thanks @omeryanar . **I also have a request for a small UI improvement:** Please let the user decide if they want that blue bar on the size column. I personally don't need that visuals, I just want the size number, however, it's not currently possible to disable it.

Thanks for the feedback !
As for your request, it's actually possible, just a bit tricky to find.
Blue bar is a default [conditional formatting](https://github.com/omeryanar/FileExplorer#conditional-formatting), if you are familiar with the same feature of Excel, you already know how to use it.

To disable it, you can right click on the Size column and choose Manage Rules:

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/4798b3be-2336-42df-ab49-e8d9c21b841b)

Then you can disable it, or remove it completely:

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/130e4a15-9940-4c71-929b-cc2a92396eba)

if you want to always use the app this way, you can save this layout for a specific folder, or the entire drive:

 https://github.com/omeryanar/FileExplorer?tab=readme-ov-file#saveload-layout 

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/a767ac68-9e3f-42ef-aba4-3e78f41769e5)

The only downside to this is that you need to do this for all drives. Maybe I can add a global layout that is saved once and applied to all drives.

**Comment by aderchox** [comment]
@omeryanar Amazing. This does the job for now.
Actually, I'm not very sensitive about it, but the reason it bothered me is it's very badly colored. It's black on blue, which is very difficult to read.
What's interesting is, this is not the case on Drives themselves, and they're correctly colored, white on blue, which is readable. But the coloring is different and unreadable in case of files within folders.
Let me show the screenshots.
Here are the drives (fine):
![image](https://github.com/omeryanar/FileExplorer/assets/52244768/b3c325f3-f1de-4cb6-857b-24b35c18b70f)
But this is some file within a folder (very unreadable):
![image](https://github.com/omeryanar/FileExplorer/assets/52244768/0a097e22-b3a7-427e-ae16-aa3f3489c5bd)
Of course I personally prefer having the global option of disabling it altogether, however, I think this is the main reason I decided to report it.
***
P.S. Also the issue of not having context menus from Windows Explorer is bothering me too, as stated in another issue, which I've already thumbed up. But all in all, I really like this tool. I'll add more suggestions later on if any new things cross my mind.

**Comment by omeryanar** [comment]
OK, now I see the problem. I didn't notice this before because I used dark mode all the time.
I replaced defult conditional formatting with the progressbar, which is used in drives. Everything should be fine now.
You can see it in v3.3

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/17b52bb0-c750-4062-9461-3cfcf0d658b9)

![image](https://github.com/omeryanar/FileExplorer/assets/34584700/429b61f8-dc94-474f-bb49-f9838da2c90e)

> P.S. Also the issue of not having context menus from Windows Explorer is bothering me too, as stated in another issue, which I've already thumbed up. But all in all, I really like this tool. I'll add more suggestions later on if any new things cross my mind.

Windows context menu is in my todo list. Feel free to report bugs or suggestions, I'll look into them as long as I have free time.

**Comment by omeryanar** [comment]
Windows Explorer context menu is implemented in v3.4
You can CTRL + Right click on files or folders to display standard Windows context menu.

https://github.com/omeryanar/FileExplorer?tab=readme-ov-file#standard-windows-and-custom-context-menu

**Comment by aderchox** [comment]
> Windows Explorer context menu is implemented in v3.4 You can CTRL + Right click on files or folders to display standard Windows context menu.
> 
> https://github.com/omeryanar/FileExplorer?tab=readme-ov-file#standard-windows-and-custom-context-menu

Thanks, great improvement! But it still seems to be buggy, at least in my experience.
If I do <kbd>ctrl + right click</kbd>it doesn't show the Windows context menu, but if I right click first (to see FE's context menu), and then do <kbd>ctrl + right click</kbd> it works! and shows the Windows context menu. So it's a two-step for me, which I guess has not been intended by you. Also, it only works on the right section. On the tree section, even the two-step hack I did above doesn't work.

**Comment by omeryanar** [comment]
> Thanks, great improvement! But it still seems to be buggy, at least in my experience. If I do ctrl + right clickit doesn't show the Windows context menu, but if I right click first (to see FE's context menu), and then do ctrl + right click it works! and shows the Windows context menu. So it's a two-step for me, which I guess has not been intended by you. Also, it only works on the right section. On the tree section, even the two-step hack I did above doesn't work.

You're right, in the previous version I only added it to the right section, and a file or folder had to be selected. In the latest version (v3.5) I've also added to the left section (file tree) and If there is no file or folder selected, the context menu for the item the mouse is directly over opens.
