### ISSUE TITLE
Tree view and tabs are not permanent

### ISSUE THREAD

**Issue by Gelsleichter** [omeryanar/FileExplorer#73]
Thanks for the app, it is a great job, congrats!

After closing and reopening the tree view is disabled and tabs closed. The theme is permanent.
The "Save Session on Close" is set as "Yes".

Thanks!

**Comment by omeryanar** [comment]
Thanks for your comments.

You are right that "Save Session on Shutdown" only takes effect when you shut down the application (right click on the notification icon in the system tray and click Exit). It should also take effect when closing main windows. I will fix this in the next version.

**Comment by omeryanar** [comment]
"Save Session on Shutdown" now saves all open folders when the window is closed (v3.5). Double-clicking the notification icon in the system tray will reopen all of them.
