### ISSUE TITLE
Cant set as default file manager

### ISSUE THREAD

**Issue by GabboNENON** [omeryanar/FileExplorer#76]
The registry scripth at #11 executes fine but when i try to open any folder it returns this error 
![Screenshot 2024-05-11 124626](https://github.com/omeryanar/FileExplorer/assets/134108340/e7ded269-cd01-4cc8-97ef-569aa35c0859)

**Comment by JaneValleyhasBtaken** [comment]
delete the 
` ` in the start and beginning

**Comment by omeryanar** [comment]
I think this issue has been resolved so I'm closing it.
