### ISSUE TITLE
Limited folder details

### ISSUE THREAD

**Issue by happydz123** [omeryanar/FileExplorer#77]
In the default windows explorer, when I right click in the bar, I can add some details like keywords, title etc and there is also a possibility to add multiple details when I click on "others" like admin, address, etc I hope you add this feature as the same as the default windows explorer.
Another thing is that when I open the FileExploer, it take a period of time to load nit as quickly as the default windows explorer do.
Thank you
a screenshot of the default windows explorer "others" details to add
![file detains](https://github.com/omeryanar/FileExplorer/assets/170321796/d327bf68-8e07-4aab-894e-c45a6d9e1ae8)

**Comment by omeryanar** [comment]
> Another thing is that when I open the FileExploer, it take a period of time to load nit as quickly as the default windows explorer do

You can activate the "Add to Startup" feature to make File Explorer open faster.

![image](https://github.com/user-attachments/assets/e8d445b2-2d46-4838-a3b0-a5203c381e4c)

> In the default windows explorer, when I right click in the bar, I can add some details like keywords, title etc

This is an enhancement that I will consider implementing in #72
