### ISSUE TITLE
How to reset default file explorer

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [omeryanar/FileExplorer#82]
Hi, previously I follow method at #11 to set the FileExplorer to default explorer. However, I want to change it back. How am I able to do that?

**Comment by Astra060** [comment]
You need to replace the changed values to "%SystemRoot%\explorer.exe"
Open registry, and follow the path being referenced in each line, when you get to "command" open the folder and replace this application's path with what I've given (Though do check the path I've given you works) keep the %1 or %*
Do this for both Drive & Directory

**Comment by Astra060** [comment]
Also next do a backup before tweaking registry

**Comment by Astra060** [comment]
Close this issue if you solved it
